using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestCA.VP
{
    public static class CommandSEC
    {
        public static string QPI = "PI";
        public static string QID = "ID";
        public static string QVFW = "VFW";
        public static string QVFW2 = "VFW2";
        public static string QMD = "MD";
        public static string QPIRI = "PIRI";
        public static string QMAR = "MAR";
        public static string QHFS = "HFS";
        public static string QCFS = "CFS";
        public static string QGS = "GS";
        public static string QPS = "PS";
        public static string QMOD = "MOD";
        public static string QWS = "WS";
        public static string QPIFS = "QPIFS";
        public static string QFLAG = "FLAG";
        public static string QFET = "FET";
        public static string QET = "ET";
        public static string QEY = "EY";
        public static string QEM = "EM";
        public static string QED = "ED";
        public static string QEH = "EH";
        public static string QGOV = "GOV";
        public static string QGOF = "GOF";
        public static string QOPMP = "OPMP";
        public static string QMPPTV = "MPPTV";
        public static string QSV = "SV";
        public static string QLST = "LST";
        public static string QDI = "DI";
        public static string QGLTV = "GLTHV";
        public static string QBATS = "BATS";
        public static string QFT = "FT";
        public static string QDM = "DM";
        public static string QT = "T";
        public static string QGPMP = "GPMP";
        public static string QHECS = "HECS";
        public static string QACCT = "ACCT";
        public static string QACLT = "ACLT";
        public static string QFPADJ = "FPADJ";
        public static string QFPPF = "FPPF";
        public static string QAAPF = "AAPF";
        public static string QPLE = "PLE";
        public static string QFWS = "FWS";
        public static string QMCHGCR = "MCHGCR";
        public static string QMUCHGCR = "MUCHGCR";
        public static string QPGS = "PGS";
        public static string QPRI = "PRI";
        public static string BTS = "BTS";
        public static string DAT = "DAT";
        public static string GOLF = "GOLF";
        public static string GOHF = "GOHF";
        public static string GOLV = "GOLV";
        public static string GOHV = "GOHV";
        public static string MPPTHV = "MPPTHV";
        public static string MPPTLV = "MPPTLV";
        public static string SIHV = "SIHV";
        public static string SILV = "SILV";
        public static string LST = "LST";
        public static string GLTHV = "GLTHV";
        public static string MCHGC = "MCHGC";
        public static string MUCHGC = "MUCHGC";
        public static string MCHGV = "MCHGV";
        public static string FT = "FT";
        public static string GPMP = "GPMP";
        public static string BCA = "BCA";
        public static string I = "I";
        public static string LON = "LON";
        public static string BATDV = "BATDV";
        public static string DMODEL = "DM";
        public static string SEP = "SEP";
        public static string ENF = "ED";
        public static string ACCT = "ACCT";
        public static string ACCB = "ACCB";
        public static string ACLT = "ACLT";
        public static string BT = "BT";
        public static string BST = "BST";
        public static string FPADJ = "FPADJ";
        public static string FPRADJ = "FPRADJ";
        public static string FPSADJ = "FPSADJ";
        public static string FPTADJ = "FPTADJ";
        public static string BDCM = "BDCM";
        public static string FPPF = "FPPF";
        public static string PALE = "PALE";
        public static string AAPF = "AAPF";
        public static string PLE = "PLE";
        public static string EPS = "EPS";
        public static string PSDV = "PSDV";
        public static string F = "F";
        public static string V = "V";
        public static string POP = "POP";
        public static string BUCD = "BUCD";
        public static string PCP = "PCP";
        public static string PSP = "PSP";
        public static string PGR = "PGR";
        public static string PBT = "PBT";
        public static string POPM = "POPM";
        public static string PF = "PF";
        public static string CLE = "CLE";
        public static string RS = "RS";
        public static string CHECKSUM_EY = "^P010";
        public static string CHECKSUM_EM = "^P012";
        public static string CHECKSUM_ED = "^P014";
        public static string CHECKSUM_EH = "^P016";

    }
}