using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication2
{
    public class CommandSEC
    {
        public static final String QPI = "PI";
  public static final String QID = "ID";
  public static final String QVFW = "VFW";
  public static final String QVFW2 = "VFW2";
  public static final String QMD = "MD";
  public static final String QPIRI = "PIRI";
  public static final String QMAR = "MAR";
  public static final String QHFS = "HFS";
  public static final String QCFS = "CFS";
  public static final String QGS = "GS";
  public static final String QPS = "PS";
  public static final String QMOD = "MOD";
  public static final String QWS = "WS";
  public static final String QPIFS = "QPIFS";
  public static final String QFLAG = "FLAG";
  public static final String QFET = "FET";
  public static final String QET = "ET";
  public static final String QEY = "EY";
  public static final String QEM = "EM";
  public static final String QED = "ED";
  public static final String QEH = "EH";
  public static final String QGOV = "GOV";
  public static final String QGOF = "GOF";
  public static final String QOPMP = "OPMP";
  public static final String QMPPTV = "MPPTV";
  public static final String QSV = "SV";
  public static final String QLST = "LST";
  public static final String QDI = "DI";
  public static final String QGLTV = "GLTHV";
  public static final String QBATS = "BATS";
  public static final String QFT = "FT";
  public static final String QDM = "DM";
  public static final String QT = "T";
  public static final String QGPMP = "GPMP";
  public static final String QHECS = "HECS";
  public static final String QACCT = "ACCT";
  public static final String QACLT = "ACLT";
  public static final String QFPADJ = "FPADJ";
  public static final String QFPPF = "FPPF";
  public static final String QAAPF = "AAPF";
  public static final String QPLE = "PLE";
  public static final String QFWS = "FWS";
  public static final String QMCHGCR = "MCHGCR";
  public static final String QMUCHGCR = "MUCHGCR";
  public static final String QPGS = "PGS";
  public static final String QPRI = "PRI";
  public static final String BTS = "BTS";
  public static final String DAT = "DAT";
  public static final String GOLF = "GOLF";
  public static final String GOHF = "GOHF";
  public static final String GOLV = "GOLV";
  public static final String GOHV = "GOHV";
  public static final String MPPTHV = "MPPTHV";
  public static final String MPPTLV = "MPPTLV";
  public static final String SIHV = "SIHV";
  public static final String SILV = "SILV";
  public static final String LST = "LST";
  public static final String GLTHV = "GLTHV";
  public static final String MCHGC = "MCHGC";
  public static final String MUCHGC = "MUCHGC";
  public static final String MCHGV = "MCHGV";
  public static final String FT = "FT";
  public static final String GPMP = "GPMP";
  public static final String BCA = "BCA";
  public static final String I = "I";
  public static final String LON = "LON";
  public static final String BATDV = "BATDV";
  public static final String DMODEL = "DM";
  public static final String SEP = "SEP";
  public static final String ENF = "ED";
  public static final String ACCT = "ACCT";
  public static final String ACCB = "ACCB";
  public static final String ACLT = "ACLT";
  public static final String BT = "BT";
  public static final String BST = "BST";
  public static final String FPADJ = "FPADJ";
  public static final String FPRADJ = "FPRADJ";
  public static final String FPSADJ = "FPSADJ";
  public static final String FPTADJ = "FPTADJ";
  public static final String BDCM = "BDCM";
  public static final String FPPF = "FPPF";
  public static final String PALE = "PALE";
  public static final String AAPF = "AAPF";
  public static final String PLE = "PLE";
  public static final String EPS = "EPS";
  public static final String PSDV = "PSDV";
  public static final String F = "F";
  public static final String V = "V";
  public static final String POP = "POP";
  public static final String BUCD = "BUCD";
  public static final String PCP = "PCP";
  public static final String PSP = "PSP";
  public static final String PGR = "PGR";
  public static final String PBT = "PBT";
  public static final String POPM = "POPM";
  public static final String PF = "PF";
  public static final String CLE = "CLE";
  public static final String RS = "RS";
  public static final String CHECKSUM_EY = "^P010";
  public static final String CHECKSUM_EM = "^P012";
  public static final String CHECKSUM_ED = "^P014";
  public static final String CHECKSUM_EH = "^P016";
  
  public CommandSEC() { }
    }
}
